### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by mashuDuek** [kevinphanle/EarthFlix#1]
1. In `GET /api/users` you are rendering all the users? I think in Netflix there is no list of users, so perhaps you want `GET /api/users/:id` to grab all info for the current user. 
2. We probably want a `GET /api/movies`. Since we have a GET for shows, and individual videos. 
3. As far as myList goes, I'm thinking maybe we switch this up a bit, and we allow users to create lists. Meaning, they don't have a single list, they can create and name lists. And add different shows/movies to lists. What do you think? I think this is gonna be an interesting challenge. We should definitely discuss before moving on with this planning.

**Comment by kevinphanle** [comment]
Okay so my_list will be synonymous to chirps in bluebird?
