### ISSUE TITLE
PA Review: User Authentification

### ISSUE THREAD

**Issue by kevinphanle** [kevinphanle/EarthFlix#4]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by mashuDuek** [comment]
Couple things:
1. Remember, when you open an issue don't tell me what you did with the code, tell me what your feature is doing. So, DB/models/controllers/views setup I don't need to know about. Same goes for Redux loop, components/containers, etc. Just tell me user auth, login/logout/signup with adequate styling. 
2. The styling isn't finished for the login page. Try scrolling to the bottom of the page. 
3. There is no error handling - good UI would be for the user to be told where they messed up and let them try again. Now, this doesn't have to be done now, you can do it after the initial two weeks. But you should absolutely do it before adding this project to your portfolio. 

Good job :)
